# Generated by Django 5.1.4 on 2025-01-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_app', '0002_hrm_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_add_department', 'Can add department'), ('can_update_department', 'Can update department'), ('can_delete_department', 'Can delete department')]},
        ),
    ]
