# Generated by Django 5.1.4 on 2025-01-23 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRM_app', '0003_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': [('can_add_department', 'can add department'), ('can_update_department', 'Can update department'), ('can_delete_department', 'Can delete department')]},
        ),
    ]
